### Zadanie 1
Utwórz v z liczbami od 1 do 10.

In [21]:
import numpy as np

v = np.arange(1,11)
print(v)

[ 1  2  3  4  5  6  7  8  9 10]

### Zadanie 2
Utwórz v liczb od 0 do 20 co 2.

In [22]:
v = np.arange(0,21,2)
print(v)

[ 0  2  4  6  8 10 12 14 16 18 20]

### Zadanie 3
Utwórz v 5 liczb losowych z rozkładu normalnego.

In [23]:
v = np.random.randn(5)
print(v)

[ 0.37316249 -0.84863357  0.51658605  0.52799962  0.49843938]

random.rand -> z rozkładu jednostajnego (w przedziale [0,1))
random.randn -> z rozkładu normalnego

### Zadanie 4
Utwórz matrix 3×3 z wartości od 1 do 9.

In [24]:
matrix = np.arange(1,10).reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

### Zadanie 5
Utwórz matrix 4×4 z liczb losowych z rozkładu jednostajnego.

In [25]:
# matrix = np.random.rand(16).reshape(4,4)
matrix = np.random.rand(4,4)
print(matrix)

[[0.59219801 0.18716953 0.54805744 0.71077647]
 [0.33290344 0.52982024 0.76859027 0.06706058]
 [0.48227746 0.16235392 0.92258063 0.77837884]
 [0.6876739  0.37987196 0.56689159 0.07386691]]

### Zadanie 6
Utwórz ramkę danych z kolumnami name, age, city. Stwórz dane dla trzech osób.

In [26]:
import pandas as pd

df = pd.DataFrame({
    "name": ["Alicja","Jakub","Marcin"],
    "age": [23,45,67],
    "city": ["Szczecin","Gdańsk","Mexico"]
})

df

     name  age      city
0  Alicja   23  Szczecin
1   Jakub   45    Gdańsk
2  Marcin   67    Mexico

### Zadanie 7
Utwórz v imion, wieków i wynagrodzeń, a następnie połącz je w ramkę danych.

In [27]:
name = ["Julia", "Maja", "Mariola"]
age = [12,45,68]
salary = [3455,6789,23456]

df=pd.DataFrame({
    "name": name,
    "age": age,
    "salary": salary
})

df

      name  age  salary
0    Julia   12    3455
1     Maja   45    6789
2  Mariola   68   23456

w rozwiązaniu names etc są stworzone za pomocą np.array

names = np.array(["Jan", "Ewa", "Piotr"])

ages = np.array([28, 34, 45])

salary = np.array([5000, 6200, 7200])

### Zadanie 8
Utwórz ramkę danych z kolumną dat zawierającą dni od 2025-01-01 do 2025-01-10. Podpowiedź - w Pythonie użyj pd.date_range, w R seq.Date.

In [28]:
date = pd.date_range(start="2025-01-01",end="2025-01-10",freq="D")

# dates = pd.date_range("2025-01-01", periods=10)

df = pd.DataFrame({
    "date": date
})

df

        date
0 2025-01-01
1 2025-01-02
2 2025-01-03
3 2025-01-04
4 2025-01-05
5 2025-01-06
6 2025-01-07
7 2025-01-08
8 2025-01-09
9 2025-01-10

### Zadanie 9
Utwórz ramkę danych z kolumnami id, x, y, gdzie x i y to liczby losowe z rozkładu normalnego.

In [29]:
x = np.random.randn(10)
y = np.random.randn(10)

df = pd.DataFrame({
    "id": np.arange(1, 11),
    "x": x,
    "y": y
})

df

   id         x         y
0   1  0.739182 -0.696549
1   2 -0.790187 -1.295716
2   3 -0.172979  0.698036
3   4 -0.830995  1.104147
4   5 -1.242823 -0.976302
5   6 -0.934736 -1.180301
6   7  1.814629 -1.375562
7   8  1.614807  0.232578
8   9 -1.764152  1.520485
9  10  0.997658  1.657735